<a href="https://colab.research.google.com/github/Akash0591/Akash-Reddy-Bommireddy/blob/main/ICP3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [24]:
import numpy as np

# Create random vector of size 15 with integers from 1-20
arr = np.random.randint(1,21,15)

# Reshape to 3 x 5
arr = arr.reshape(3,5)

# Print shape
print("SHAPE:-",arr.shape)

# Replace max in each row with 0
for i in range(arr.shape[0]):
    arr[i, arr[i,:].argmax()] = 0

print(arr)

SHAPE:- (3, 5)
[[15  9  8 15  0]
 [11  2  0 16  6]
 [19  3 12  0  6]]


In [23]:

import numpy as np

# Create 4x3 array of 4-byte integers
int_array = np.empty((4, 3), dtype=np.int32)

# Print array shape, type, and data type
print("ARRAY SHAPE:-",int_array.shape)
print("TYPE:-",type(int_array))
print("DATA TYPE:-",int_array.dtype)

ARRAY SHAPE:- (4, 3)
TYPE:- <class 'numpy.ndarray'>
DATA TYPE:- int32


In [21]:
import numpy as np

arr = np.array([[0, 1, 2],
                [3, 4,5]])

# Get the diagonal elements
diagonal = np.diag(arr)

# Compute sum
sum_diagonal = np.sum(diagonal)

print("sum of diagonals:-",sum_diagonal)

sum of diagonals:- 4


In [20]:
import numpy as np

# a. Create an array of odd and even numbers from 10 to 70
even_nums = np.arange(10, 71, 2)
odd_nums = np.arange(11, 70, 2)
arr = np.concatenate([even_nums])
arr1 = np.concatenate([odd_nums])
print("even:-",arr)
print("odd:-",arr1)

# b. Perform element-wise operations on two equal sized arrays
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

add = arr1 + arr2
subtract = arr1 - arr2
multiply = arr1 * arr2

print("addition:-",add)
print("subtraction:-",subtract)
print("multiplication:-",multiply)

# c. Sort array by row and column
array = np.array([[5.54, 3.38, 7.99],
                 [3.54, 4.38, 6.99],
                 [1.54, 2.39, 9.29]])

print("sort by column:-",np.sort(array, axis=0)) # Sort by column
print("sort by row:-",np.sort(array, axis=1)) # Sort by row

even:- [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50 52 54 56
 58 60 62 64 66 68 70]
odd:- [11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47 49 51 53 55 57
 59 61 63 65 67 69]
addition:- [5 7 9]
subtraction:- [-3 -3 -3]
multiplication:- [ 4 10 18]
sort by column:- [[1.54 2.39 6.99]
 [3.54 3.38 7.99]
 [5.54 4.38 9.29]]
sort by row:- [[3.38 5.54 7.99]
 [3.54 4.38 6.99]
 [1.54 2.39 9.29]]


In [15]:
import numpy as np

# declare the array
arr = np.array([[4, 2, np.nan, 1],
                [11, 12, 14, 9],
                [5, np.nan, 1, np.nan]])

# find the missing data
missing_data = np.isnan(arr)

# print the Boolean output
print("Missing data: ", missing_data)

Missing data:  [[False False  True False]
 [False False False False]
 [False  True False  True]]
