<a href="https://colab.research.google.com/github/Akash0591/Akash-Reddy-Bommireddy/blob/main/ML_ICP_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Part_A**

In [5]:
import numpy as np

# 1. Create a random vector of size 15 with integers in the range 1-20
random_vector = np.random.randint(1, 21, size=15)
print("Original random vector:", random_vector)

# 2. Reshape the array to 3 by 5
reshaped_array = random_vector.reshape(3, 5)
print("\nReshaped array (3 x 5):\n", reshaped_array)

# 3. Print array shape
print("\nArray shape:", reshaped_array.shape)

# 4. Replace the max in each row by 0
row_max = reshaped_array.max(axis=1, keepdims=True)
reshaped_array = np.where(reshaped_array == row_max, 0, reshaped_array)
print("\nArray with max in each row replaced by 0:\n", reshaped_array)

# Create a 2D array of size 4 x 3 (composed of 4-byte integer elements)
new_array = np.random.randint(1, 101, size=(4, 3), dtype=np.int32)
print("\n2D array (4 x 3):\n", new_array)

# Print the shape, type, and data type of the new array
print("\nShape:", new_array.shape)
print("Type:", type(new_array))
print("Data type:", new_array.dtype)

Original random vector: [ 1  5  9  1  3  3  6 20  9  9  6 14  3 19 15]

Reshaped array (3 x 5):
 [[ 1  5  9  1  3]
 [ 3  6 20  9  9]
 [ 6 14  3 19 15]]

Array shape: (3, 5)

Array with max in each row replaced by 0:
 [[ 1  5  0  1  3]
 [ 3  6  0  9  9]
 [ 6 14  3  0 15]]

2D array (4 x 3):
 [[29 61 59]
 [72 39 21]
 [16 95 65]
 [27 40 33]]

Shape: (4, 3)
Type: <class 'numpy.ndarray'>
Data type: int32


In [6]:
import numpy as np

# Given square matrix
A = np.array([[3, -2], [1, 0]])

# Compute eigenvalues and right eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)

print("Matrix A:")
print(A)

print("\nEigenvalues:")
print(eigenvalues)

print("\nRight Eigenvectors:")
print(eigenvectors)

Matrix A:
[[ 3 -2]
 [ 1  0]]

Eigenvalues:
[2. 1.]

Right Eigenvectors:
[[0.89442719 0.70710678]
 [0.4472136  0.70710678]]


In [9]:
import numpy as np

# Given array
array = np.array([[0, 1, 2], [3, 4, 5]])

# Compute sum of the diagonal elements
diagonal_sum = np.trace(array)

print("Sum of Diagonal Elements:", diagonal_sum)


Sum of Diagonal Elements: 4


In [10]:
import numpy as np

# Original array
arr = np.array([[1, 2],
                [3, 4],
                [5, 6]])

print("Original array:")
print(arr)
print("Shape:", arr.shape)

# Reshape to 3x2
arr_3x2 = arr.reshape(3, 2)
print("\nReshaped to 3x2:")
print(arr_3x2)
print("Shape:", arr_3x2.shape)

# Reshape to 2x3
arr_2x3 = arr.reshape(2, 3)
print("\nReshaped to 2x3:")
print(arr_2x3)
print("Shape:", arr_2x3.shape)

Original array:
[[1 2]
 [3 4]
 [5 6]]
Shape: (3, 2)

Reshaped to 3x2:
[[1 2]
 [3 4]
 [5 6]]
Shape: (3, 2)

Reshaped to 2x3:
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)


**Part_B**

In [11]:
import pandas as pd

# 1. Read the CSV file
df = pd.read_csv('data.csv')

# 2. Show basic statistical description
print("Basic Statistical Description:")
print(df.describe())

# 3. Check for null values
print("\nNull Values:", df.isnull().sum())

# 3.a. Replace null values with mean
df = df.fillna(df.mean())

# 4. Aggregate data for selected columns
print("\nAggregated Data:")
print(df[['Calories', 'Pulse']].agg(['min', 'max', 'count', 'mean']))

# 5. Filter rows with calories between 500 and 1000
print("\nRows with Calories between 500 and 1000:")
filtered_df = df[(df['Calories'] >= 500) & (df['Calories'] <= 1000)]
print(filtered_df)

# 6. Filter rows with calories > 500 and pulse < 100
print("\nRows with Calories > 500 and Pulse < 100:")
filtered_df = df[(df['Calories'] > 500) & (df['Pulse'] < 100)]
print(filtered_df)

# 7. Create a new dataframe without 'Maxpulse' column
df_modified = df.drop('Maxpulse', axis=1)
print("\ndf_modified (without 'Maxpulse' column):")
print(df_modified.head())

# 8. Delete 'Maxpulse' column from the main dataframe
df = df.drop('Maxpulse', axis=1)
print("\nMain dataframe (without 'Maxpulse' column):")
print(df.head())

# 9. Convert 'Calories' column to int datatype
df['Calories'] = df['Calories'].astype(int)
print("\nDatatype of 'Calories' column:", df['Calories'].dtype)

Basic Statistical Description:
         Duration       Pulse    Maxpulse     Calories
count  169.000000  169.000000  169.000000   164.000000
mean    63.846154  107.461538  134.047337   375.790244
std     42.299949   14.510259   16.450434   266.379919
min     15.000000   80.000000  100.000000    50.300000
25%     45.000000  100.000000  124.000000   250.925000
50%     60.000000  105.000000  131.000000   318.600000
75%     60.000000  111.000000  141.000000   387.600000
max    300.000000  159.000000  184.000000  1860.400000

Null Values: Duration    0
Pulse       0
Maxpulse    0
Calories    5
dtype: int64

Aggregated Data:
          Calories       Pulse
min      50.300000   80.000000
max    1860.400000  159.000000
count   169.000000  169.000000
mean    375.790244  107.461538

Rows with Calories between 500 and 1000:
     Duration  Pulse  Maxpulse  Calories
51         80    123       146     643.1
62        160    109       135     853.0
65        180     90       130     800.4
66        15